name: Android-apk-build

on:
  workflow_dispatch:

jobs:
  build-android:
    name: 🤖 Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      # Optional: Clean build cache
      - name: Flutter clean
        run: flutter clean

      # Build release APK
      - name: Build release APK
        run: flutter build apk --release

      # Rename APK for clarity
      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/MyAppRelease.apk

      # Upload APK to GitHub Release
      - name: Upload APK to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/MyAppRelease.apk
          tag: v${{ github.run_number }}
          overwrite: true
          body: "🚀 First Android release"
